version: "3.9"

services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    volumes:
      - ./vstorage:/mnt/vstorage
    depends_on:
      - service2
      - storage

  service2:
    build: ./service2
    volumes:
      - ./vstorage:/mnt/vstorage
    depends_on:
      - storage

  storage:
    build: ./storage
    volumes:
      - storage-data:/data

volumes:
  vstorage:
  storage-data:
